import type { Site, Photo, Review } from "./types";

// Demo site data for /site/demo
export const DEMO_SITE: Site = {
  id: "demo",
  user_id: "demo",
  slug: "demo",
  custom_domain: null,
  company_name: "Smith Renovations",
  headline: "Quality Home Renovations in Sydney",
  about_text: `With over 15 years of experience, Smith Renovations has been transforming homes across Sydney and surrounding areas. We specialise in bathroom renovations, kitchen fitting, and complete home makeovers.

Our team of skilled tradespeople takes pride in delivering exceptional craftsmanship on every project. From initial consultation to final handover, we work closely with you to bring your vision to life.

We're fully licensed, insured, and committed to completing every job on time and within budget. Our reputation is built on quality work and happy customers.`,
  services: [
    {
      name: "Bathroom Renovations",
      description: "Complete bathroom transformations including tiling, plumbing, vanities, and waterproofing. We handle everything from design to completion.",
    },
    {
      name: "Kitchen Fitting",
      description: "Custom kitchen installations with quality cabinetry, benchtops, splashbacks, and appliance fitting. Modern designs tailored to your space.",
    },
    {
      name: "General Renovations",
      description: "Full home renovations including flooring, painting, plastering, and structural modifications. Transform any room in your home.",
    },
    {
      name: "Tiling",
      description: "Professional tiling for floors, walls, and outdoor areas. We work with all tile types including porcelain, ceramic, and natural stone.",
    },
  ],
  service_areas: ["Sydney CBD", "North Shore", "Eastern Suburbs", "Inner West"],
  phone: "+61 400 123 456",
  email: "hello@smithrenovations.com.au",
  address: "Sydney, NSW",
  facebook_url: "https://facebook.com",
  instagram_url: "https://instagram.com",
  template: "modern",
  primary_color: "#3b82f6",
  logo_url: null,
  quotesnap_user_id: null,
  show_quote_button: true,
  google_reviews_url: "https://google.com",
  is_published: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_PHOTOS: Photo[] = [
  {
    id: "demo-1",
    site_id: "demo",
    user_id: "demo",
    url: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
    thumbnail_url: null,
    category: "bathroom",
    caption: "Modern bathroom renovation with walk-in shower and floating vanity",
    is_before_after: false,
    pair_id: null,
    is_before: null,
    sort_order: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    site_id: "demo",
    user_id: "demo",
    url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    thumbnail_url: null,
    category: "kitchen",
    caption: "Contemporary kitchen with stone benchtops and custom cabinetry",
    is_before_after: false,
    pair_id: null,
    is_before: null,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    site_id: "demo",
    user_id: "demo",
    url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
    thumbnail_url: null,
    category: "bathroom",
    caption: "Luxurious ensuite with freestanding bath and feature tiles",
    is_before_after: false,
    pair_id: null,
    is_before: null,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    site_id: "demo",
    user_id: "demo",
    url: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80",
    thumbnail_url: null,
    category: "kitchen",
    caption: "Open plan kitchen renovation with island bench",
    is_before_after: false,
    pair_id: null,
    is_before: null,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-5",
    site_id: "demo",
    user_id: "demo",
    url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    thumbnail_url: null,
    category: "exterior",
    caption: "Complete home exterior renovation",
    is_before_after: false,
    pair_id: null,
    is_before: null,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-6",
    site_id: "demo",
    user_id: "demo",
    url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
    thumbnail_url: null,
    category: "flooring",
    caption: "Timber flooring installation throughout living areas",
    is_before_after: false,
    pair_id: null,
    is_before: null,
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "demo-review-1",
    site_id: "demo",
    client_name: "Sarah M.",
    client_location: "Mosman",
    rating: 5,
    text: "Absolutely thrilled with our new bathroom! The team was professional, clean, and finished on time. James kept us informed throughout the entire process. Highly recommend Smith Renovations to anyone looking for quality work.",
    project_type: "Bathroom Renovation",
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-review-2",
    site_id: "demo",
    client_name: "Michael & Jenny T.",
    client_location: "Bondi",
    rating: 5,
    text: "We had our kitchen completely transformed and couldn't be happier. The attention to detail was impressive, and they worked within our budget. Our friends can't believe it's the same house!",
    project_type: "Kitchen Renovation",
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-review-3",
    site_id: "demo",
    client_name: "David L.",
    client_location: "Surry Hills",
    rating: 5,
    text: "Third time using Smith Renovations and they never disappoint. Just finished tiling our outdoor area and it looks amazing. Fair pricing and excellent communication throughout.",
    project_type: "Outdoor Tiling",
    created_at: new Date().toISOString(),
  },
];
